import React, { Component } from 'react'
import bg from '../images/main.png'
import black from '../images/black.jpg'

export class Story extends Component {
  render() {
    return (
      <div>
        <img alt="" src={bg} className="story_bg"/>
        <img alt="" src={black} className="story_black"/>

        <div className="story_season">
        <h2>Season 1</h2>
            <p>Season 1 spans a period of several months on a world where the seasons last for years at a time. The action begins in the unified Seven Kingdoms of Westeros as the long summer ends and winter draws near. Lord Eddard Stark is asked by his old friend, King Robert Baratheon, to serve as the Hand of the King following the death of the previous incumbent, Eddard's mentor Jon Arryn. Eddard is reluctant but receives intelligence suggesting that Jon was murdered. Eddard accepts Robert's offer, planning to use his position and authority to investigate the alleged murder.</p>
            <p>Meanwhile, on the eastern continent of Essos, the exiled children of House Targaryen, which Robert destroyed to claim the throne, are plotting to return to Westeros and unseat the 'usurper'. To this end, Viserys Targaryen arranges the marriage of his sister Daenerys to Khal Drogo, the leader of 40,000 Dothraki warriors, in return for the use of his warriors in invading Westeros. For her part, Daenerys just wants to find a safe refuge far away from King Robert's assassins and her brother's scheming ambition.</p>
            <p>Finally, on the northern-most border of the Seven Kingdoms the sworn brothers of the Night's Watch guard the Wall, a 300-mile-long colossal fortification of ice which has stood for thousands of years. The Watch defends the Wall against the depredations of the lawless wildlings who live beyond, but rumor speaks of a new threat arising in the lands of perpetual winter.</p>
        </div>

        <div className="story_season">
        <h2>Season 2</h2>
            <p>Season 2 spans several months on a world where the seasons last for years at a time. The Seven Kingdoms are at war, with the King in the North, Robb Stark, fighting to win independence for his people and those of the Riverlands. Robb decides that he must win the allegiance of the fiercely independent ironborn to his cause, and sends his best friend Theon Greyjoy to treat with his father, who is hatching plans of his own. Meanwhile, Joffrey Baratheon holds the Iron Throne with the backing of the powerful House Lannister, but his uncle Renly has also claimed the throne with the support of House Tyrell, whose armies are much larger. As they struggle for the throne, Tyrion Lannister arrives in King's Landing to take matters in hand, only to face opposition from his scheming sister, Cersei, now the Queen Regent.</p>
            <p>However, there is another faction entering the picture. Stannis Baratheon, Robert's younger brother and Renly's older brother, has also claimed the Iron Throne. A proven battle commander and veteran of several wars, Stannis is known to be utterly without mercy to his enemies and will do what is right even if it destroys him. Advising him is Melisandre, an enigmatic priestess from the east, who believes Stannis is meant for a greater destiny, and Ser Davos Seaworth, an honest and honorable man uneasy with the shifts in power at Stannis' court.</p>
            <p>Far to the east, Daenerys Targaryen has hatched the only three dragons in the world. Eventually they will grow into terrifying monsters capable of destroying cities at her command, but for now they are still hatchlings and vulnerable. With her khalasar gone, Daenerys and her small band of followers must find a way across a forbidding wasteland and find new allies to support her claim to the Iron Throne.</p>
            <p>In the distant north, the Night's Watch has mounted an expedition beyond the Wall, searching for missing rangers and investigating rumors of wildlings gathering in the mountains. For Jon Snow this will be a rite of passage as he is asked to make difficult choices, for the realm and for himself.</p>
        </div>

        <div className="story_season">
        <h2>Season 3</h2>
            <p>Season 3 spans several months on a world where the seasons can last for years at a time. Autumn has fallen across the world, with winter not far behind. The people should be preparing for years of snow and ice, but the Seven Kingdoms of Westeros instead remain gripped by civil war. Would-be king Renly Baratheon has been assassinated, altering the alliances in the war. The cruel boy-king Joffrey Baratheon has won a great victory by securing an alliance with House Tyrell, with his supporters defeating his uncle Stannis in an epic battle. Joffrey now commands the largest armies in the realm and his triumph appears inevitable.</p>
            <p>King Robb Stark remains in the field, however his homeland, the North, is partially under ironborn occupation. Robb needs to decide on a course of action to win an overall victory. He must also win back the allegiance of House Frey, whom he has offended by breaking his marriage pact with them. King Robb has won every battle he has fought, but as with old King Robert, the Starks will have to see if good soldiers make good kings.</p>
            <p>Stannis Baratheon may be defeated and most of his army destroyed or scattered, but he is not out of the fight yet. Having retreated to his headquarters on Dragonstone island with his handful of surviving soldiers, Stannis' status as the last legitimate heir to his older brother Robert still casts a shadow over Joffrey's claim to the throne. With the priestess Melisandre at his side, Stannis can still influence the course of the war by striking where least expected.</p>
            <p>The lives of many others still hang in the balance. Bran Stark and his protectors must cross the frozen wastelands of the North to reach the Wall, while Arya must brave the war-torn Riverlands in search of her mother and brother. Brienne of Tarth also has the thankless task of escorting the captive Jaime Lannister home across hundreds of miles of battlefields and carnage. Theon Greyjoy must face the consequences of his actions at Winterfell. And in King's Landing both Tyrion Lannister and Sansa Stark must brave the currents of a much more dangerous court in order to survive.</p>
            <p>On the eastern continent, Daenerys Targaryen has fled the political viper-pit of Qarth. Her dragons are growing and her fame is spreading, but to take the Iron Throne she will need supporters and an army. Both may be found in the corrupt cities of Slaver's Bay... for a price.</p>
            <p>Beyond the Wall, the White Walkers are on the move, threatening both the Seven Kingdoms and the lands of the Free Folk. While the Night's Watch faces the threat of the White Walkers in the field, Jon Snow must infiltrate the wildling army of Mance Rayder and discover the King-Beyond-the-Wall's plans.</p>
        </div>


        <div className="story_season">
        <h2>Season 4</h2>
            <p> The War of the Five Kings is drawing to a close, but new intrigues and plots are in motion, and the surviving factions must contend with enemies not only outside their ranks, but within</p>
            <p>King in the North Robb Stark is dead, betrayed by his own bannermen the Boltons and Freys while he was a guest under the Freys' roof. Robb's mother Catelyn and his wife Talisa, along with most of the Northern leadership were also killed at the massacre now known as the Red Wedding, along with the entire Northern army</p>
            <p>Having already defeated Stannis Baratheon at the Battle of the Blackwater and secured southern Westeros, House Lannister stands triumphant. The crazed boy-king Joffrey Baratheon gloats, though the victory truly belongs to his grandfather, Lord Tywin Lannister, Hand of the King and the real power behind the Iron Throne. As reward for their betrayal, Tywin has granted the Boltons rule of the North, and the Freys with nominal rule of Riverrun, though the castle remains under the command of Brynden Tully</p>
            <p>Though the mainland of Westeros is mostly under Lannister control, there are still two factions defying them: the Greyjoys and the Baratheons. Ironborn occupiers remaining in the North are being hunted down by Ramsay Snow, bastard son of Roose Bolton. Ramsay holds Theon Greyjoy hostage, horribly torturing him at whim, but Balon Greyjoy considers his son as good as dead</p>
            <p>Stannis Baratheon, as the rightful heir to his older brother King Robert, still refuses to surrender, despite having only the remnants of an army. However, following the advice of Melisandre, he has focused his attention of the threat of the wildlings marching against the Wall</p>
            <p>The Lannisters only managed to win on the battlefield with the key support of House Tyrell of the Reach, which they won through promising a marriage-alliance between King Joffrey and Margaery Tyrell, daughter of Lord Mace Tyrell. Queen Regent Cersei fears - correctly - that just as the Baratheons became dependent on the Lannisters after Robert's Rebellion, the Lannisters are starting to become dependent on the Tyrells, who are already insinuating themselves into positions of power at King's Landing. A royal wedding is to be held between Joffrey and Margaery, which will confirm the future of the realm</p>
            <p>The only two kingdoms which have remained entirely aloof from the war so far are the Vale of Arryn and Dorne. While Lysa Arryn chose to remain neutral, former Master of Coin and new Lord of Harrenhal Petyr Baelish has been sent by Lord Tywin to woo her with a marriage proposal, now that he's a high lord and a suitable match for the Lady Regent of the Vale. Nevertheless only Littlefinger knows what Littlefinger is plotting.</p>
            <p>For their own part, House Martell of Dorne has loathed the Lannisters ever since the Sack of King's Landing, when Ser Gregor Clegane raped and killed Elia Martell - sister of Doran Martell, the ruling Prince of Dorne - and Lord Tywin did nothing to punish him. During the War of the Five Kings Tyrion Lannister prevented Dorne from declaring for any of House Lannister's enemies by sending Princess Myrcella to Sunspear as part of her betrothal to Prince Trystane Martell, and in return, the Martells were promised a seat on the Small Council. To the consternation of the Lannisters, a large Dornish embassy arrives in King's Landing to claim their due - but instead of the elderly Prince Doran, his brash younger brother Prince Oberyn comes to claim the council seat. Oberyn loves the ladies, he loves the boys, but most of all he loved his sister Elia, and the Lannisters aren't the only ones who pay their debts</p>
            <p>Meanwhile, across the Narrow Sea in Slaver's Bay, perhaps the greatest threat to Lannister rule is rapidly growing in strength. Daenerys Targaryen now commands not just three live dragons - who are starting to grow large enough to serve as decisive weapons of war - but also an army of eight thousand Unsullied warrior-eunuchs. For now, Queen Daenerys is carving a path through Slaver's Bay - not of conquest but of liberation. As functionally once a slave herself, Daenerys is determined to free the downtrodden slaves of the region. First Astapor and then Yunkai fell before Daenerys's forces, and hundreds of thousands of freed slaves now flock to her banner. Yet Daenerys must now face the last and greatest of the slaver-cities, Meereen - and unlike her previous victories, they have had time to prepare for her arrival</p>
            <p>Far to the north, beyond the politics and meaningless feuds of the south, the Wall and the dwindling Night's Watch are all that stand between the Seven Kingdoms and the horrors beyond. The White Walkers have emerged in force, leading their armies of wights. The wildlings have rallied behind King-Beyond-the-Wall Mance Rayder in an attempt to flee south, knowing that as the White Walkers advance, anyone who remain in the lands beyond the Wall will die and become part of the undead host. Mance's wildling army now numbers in the tens of thousands, and is determined to force its way through the Wall to reach the safety of the south. All that stands between the Seven Kingdoms and this barbarian invasion is the Night's Watch, whose numbers and leadership were recently devastated with the deaths of a third of their number and that of Lord Commander Jeor Mormont. Jon Snow and Samwell Tarly do what they can to prepare Castle Black for the massive wildling attack.</p>
            <p>Not only are the Night's Watch outnumbered and their remaining leadership fractured, but advanced raiding bands of wildlings have infiltrated behind the Wall by climbing over it, preparing to attack the weakly defended southern side of Castle Black. These warbands are led by Tormund and the fearsome Styr, Magnar of Thenn - as well as Jon Snow's ex-lover Ygritte, whom he betrayed when he revealed his true loyalty and returned to the Night's Watch</p>
            <p>In the Seven Kingdoms, while House Stark stands on the verge of extinction - and is believed to be just that by the realm at large - four "lone wolves" fight to survive: Sansa Stark remains a hostage of the Iron Throne and a forced marriage to Tyrion Lannister, Rickon Stark seeks the safety of Last Hearth and the fiercely loyal House Umber, Bran Stark and his companions Hodor, Jojen and Meera Reed have crossed the Wall chasing a vision, and Arya Stark, having lost everything and forced to rely on the protection of a man she hates, clings to survival and her thirst for vengeance</p>
        </div>

        <div className="story_season">
        <h2>Season 5</h2>
            <p>The War of the Five Kings, once thought to be drawing to a close, is instead entering a new and more chaotic phase. Westeros is on the brink of collapse, and many are seizing what they can while the realm implodes, like a corpse making a feast for crows.</p>
            <p>Tywin Lannister is dead, shot on the privy by his long-abused dwarf son Tyrion. The crazed boy-king Joffrey Baratheon, Tywin's grandson, is also dead after being poisoned at his own wedding, and succeeded by his younger and more pliable brother, Tommen. Queen Cersei Lannister succeeds her father as the head of House Lannister, and once again takes over as Queen Regent, as Tommen has yet to come of age. Cersei has been blocked by several powerful men over the years, including her husband King Robert Baratheon and his friend Eddard Stark, but due to her betrayals they are both dead. Now with even Tywin and Joffrey dead, and Tyrion fleeing the realm, there are no more checks on Cersei's power, and she is essentially the Ruling Queen of the Seven Kingdoms in all but name. However, Cersei is neither a master strategist nor a skilled diplomat (unlike her father and brother) and she faces mounting crises that would have strained even their abilities.</p>
            <p> House Lannister and its allies have managed to crush House Stark, but in many ways it was a pyrrhic victory. The Iron Throne was already in massive debt to foreign banks before the war even began, and the Lannisters' immense wartime spending increased the crown's debts to crippling levels. The Lannisters must now desperately attempt to placate the Iron Bank of Braavos, by far the largest of the foreign banks, and the one which the crown owes most of its huge debts to.</p>
            <p>The game of thrones is, unfortunately, not a simple game of cyvasse in which the pieces can be quickly reassembled: vast swathes of Westeros have been devastated by civil war, and it may take a full generation for them to rebuild. The Riverlands, where most of the war was fought, have been reduced to a burned out husk. Nominally the Lannisters and their House Frey allies control the Riverlands, but it has been reduced to a lawless and corpse-filled devastation, hardly controlled by anyone. Winter is fast approaching, but instead of stockpiling harvests the past few years, the great lords have been busy destroying one of the main breadbasket regions of the Seven Kingdoms. Combined with the realm's massive debts to foreign banks, starvation level conditions are starting to set in for the smallfolk across the realm. Outraged by the willful indifference of their rulers to their well-being for so long, commoners are starting to fall back onto old cultural touchstones, channeling their frustration into religious fanaticism. A popular disgust movement spreads across Westeros, and makes its way to the capital.</p>
            <p> Adding to these woes is the increasing rivalry between the Lannisters and their Tyrell allies, specifically between Cersei and Margaery Tyrell. The Lannisters only managed to win on the battlefield with the armies and food resources won by their alliance with the House Tyrell of the Reach. Now that Tywin is dead, and Margaery is soon to be King Tommen's queen, the Tyrells are no longer pretending to be polite to the Lannisters, but openly demanding greater concessions and key positions of power. With half of the Lannister armies slaughtered by Robb Stark during the war, their financial resources depleted, and the Tyrells controlling the only major breadbasket region untouched by the war, the Lannisters are having to face the reality that the Tyrells hold numerous advantages over them. Just as Robert Baratheon became king only to become dependent on the support of the Lannisters, the Lannisters have now become dependant on the Tyrells.</p>
            <p> Without the political acumen of Tywin or Tyrion, Queen Regent Cersei struggles to address these major challenges. Adding even further to her woes is that the king's Small Council has been gutted, with Hand of the King Tywin dead, Master of Coin Petyr Baelish leaving for the Eyrie, and both Tyrion and Master of Whisperers Varys fleeing the capital city. Of the original Small Council when the Lannisters first seized power, only Grand Maester Pycelle remains.</p>
            <p>Besides the Reach, only the regions which have remained neutral so far still have all of their armies and resources intact: the Vale, ruled by House Arryn, and Dorne, ruled by House Martell. With nearly all the other Great Houses defeated or half-exhausted, the fresh armies of the Vale and Dorne can drastically alter the political playing field, depending on which side they choose to join.</p>
            <p> The ultimate result of the war was to exhaust the Starks, Lannisters, and other Great Houses of the Seven Kingdoms - exactly as Petyr "Littlefinger" Baelish had planned. The secret architect of the conflict, it was Littlefinger who was responsible for poisoning Robert's Hand, Jon Arryn, by conspiring with his own wife Lysa Arryn. Littlefinger then engineered the betrayal of Eddard Stark, only to later assist Olenna Tyrell in assassinating King Joffrey at his own wedding. Baelish has now murdered Lysa, mere days after wedding her, and seized power over the Vale as regent for her young son. For the moment, Baelish remains in the Vale, consolidating his new hold over the Vale lords through his stepson Robin and his position as Lord Protector of the Vale. Alongside Baelish is the black-haired "Alayne", his ward and "niece" - secretly, Sansa Stark, who fell into Littlefinger's custody after he helped her escape her long imprisonment at Joffrey's royal court.</p>
            <p> In the deserts of the deep south of Westeros, the people of Dorne demand vengeance for the death of Prince Oberyn, who died in a trial by combat at the hands of Ser Gregor Clegane. Leading the call to enter the war against the Lannisters are Oberyn's paramour, Ellaria Sand, and the eldest of his eight daughters: Obara, Nymeria, and Tyene. But Doran Martell, the Prince of Dorne and Oberyn's older brother, continues to urge restraint. Further complicating the matter is that early in the war, the Lannisters bribed the Martells into staying neutral by offering a marriage-alliance, sending Cersei's daughter Myrcella to Dorne to betroth her to Doran's son Trystane. Myrcella is still a ward living in Dorne's capital, Sunspear.</p>
            <p>The most dire situation in Westeros, however, is in the North and at the Wall. The massive assault against Castle Black by the wildling army of Mance Rayder was defeated at the last moment by the surprise arrival of Stannis Baratheon and his remaining forces. Stannis withdrew from his island stronghold Dragonstone to reach the Wall by sea, to defend the realm of which he feels he is the only rightful king. With his home territories in the Stormlands overrun, Stannis needs to win the allegiance of Robb Stark's defeated bannermen, to rally the North again as a springboard against Lannister rule, as well as the support of Jon Snow, who therefore must walk a political tightrope between Stannis and his vows, since the Night's Watch is sworn to strict political neutrality. Though the battle against the wildlings is all but over, the Night's Watch is in its own dire conditions. With almost all of the Watch's top officers either killed or missing, among them Lord Commander Jeor Mormont and First Ranger Benjen Stark, the organization has been left leaderless during this time of crisis, and therefore will have to navigate a contentious election for a new Lord Commander. All the while, the White Walkers and their ever-growing army of the dead are bearing down on the Wall itself, intent on spilling over it to destroy the lands of men beyond, who remain ignorant of the long-forgotten but all-too-real danger.</p>
            <p>The main armies of the Northern Houses, however, were slaughtered in the south at the Red Wedding, and the large main army of House Bolton has just returned to the North following the recapture of Moat Cailin. The Boltons switched to the Lannister side during the betrayal at the Red Wedding, during which their leader Lord Roose Bolton personally killed Robb Stark, and they have been installed as the new rulers of the North in the name of King Tommen and the Lannisters. With the other Northern Houses defeated and weakened, the Lannister-backed Bolton army can now suppress any feeble opposition to their rule. Meanwhile, Roose's sociopathic bastard son Ramsay Snow - now legitimized as Ramsay Bolton - is the new Lord of Winterfell under his father, reoccupying the castle which he personally burned out previously. With the Boltons in power, Ramsay is now free to commit numerous atrocities throughout the North, such as flaying men alive and hunting and killing young women for sport.</p>
            <p>However, the struggle for the North is not yet over. Various areas of the North's western coast are still held by ironborn invaders under Balon Greyjoy, who chose to crown himself as King of the Iron Islands and attack the North during Robb Stark's march south rather than ally with him against the Lannisters. Balon's son and heir, Theon, who himself was a ward of Lord Eddard Stark and one of Robb's closest advisors, turned on the Starks and led the assault himself but was betrayed by his own men and is now a prisoner of the Boltons, having been brutally flayed, tortured, and psychologically broken by Ramsay himself, who has reduced Theon to his personal slave, "Reek".</p>
            <p>East of Westeros, after murdering his own father, Tyrion Lannister has fled across the Narrow Sea to the Free Cities, his future intentions unknown even to himself. Accompanied by Varys, he arrives in the east, unaware that the erstwhile Master of Whisperers might yet have secrets to reveal. Further north, meanwhile, representatives from the Iron Throne travel to the Free City of Braavos to assuage the Iron Bank's frustrations about all of the money the Lannisters owe. Unbeknownst to all, Arya Stark has also fled to Braavos, due to a favor she was owed for saving the life of one of the mysterious guild of assassins in Braavos known as the Faceless Men.</p>
            <p> Further east in Slaver's Bay, Daenerys Targaryen's hold over Meereen has become very precarious, as ruling the city is becoming much more difficult than conquering it was. Sectarian violence is rampant between the former slaves and former slave-masters, revenge attacks are on the rise, and the resurgent slavers at Yunkai are rallying all those who oppose her. Daenerys's three dragons, now growing to dangerous size, have become uncontrollable and she can no longer rely upon them to defeat her enemies on the battlefield. Drogon burned a child to death while he was hunting and fled the city, forcing Daenerys to chain up the remaining two dragons in the caverns underneath the city. In addition, Daenerys is still distraught over the recent revelations concerning her once-trusted advisor Jorah Mormont, whom she exiled from the city as punishment. Her remaining advisors Ser Barristan Selmy, Missandei, and the sellsword Daario Naharis attempt to help hold her reign together.</p>
            <p> But unbeknownst to Daenerys, word has finally spread to Westeros that the last living Targaryen heir has hatched three live dragons. No longer a mere curiosity halfway across the world, several different factions in Westeros are now pondering how Daenerys and her dragons will factor into the already confusing and multi-sided civil war still tearing the Seven Kingdoms apart. Envoys are beginning to head east to court Daenerys's allegiance: but those who try to dance with dragons run the risk of being burned.</p>
        </div>

        <div className="story_season">
        <h2>Season 6</h2>
            <p>Winter has come.</p>
            <p>Westeros braces for a winter which may become a new Long Night, as the White Walkers and their army of the dead are poised to strike against the Wall and the realms of men.</p>
            <p>In King's Landing, Queen Cersei Lannister has been publicly shamed by the Faith of the Seven and awaits her trial for regicide and incest. Even Grand Maester Pycelle has abandoned her, and called her uncle, Ser Kevan Lannister, to rule as the new Hand of the King. Even though Cersei has been released to their custody, her inept leadership nearly destroyed House Lannister's hold on the throne and they have no intention of ever letting her wield power again. Kevan and Pycelle must attempt to mend the damage Cersei did to the Lannister-Tyrell alliance. The Lannisters and Tyrells on Kevan's Small Council maintain a shaky truce as they attempt to deal with the ongoing debt crisis to the Iron Bank of Braavos, as well as the rise of the fanatical Faith Militant due to Cersei's blunders. Cersei meanwhile, though seemingly humbled, still has a few schemes she will attempt to play to regain control.</p>
            <p>In the North, the Boltons have triumphed over King Stannis — but in the distraction, Sansa Stark and Theon Greyjoy have escaped, desperately jumping off Winterfell's castle walls. Brienne of Tarth, who executed Stannis, must now deal with the consequences of putting her vow to avenge King Renly before her oath to protect Sansa.</p>
            <p>In the Riverlands, after the Red Wedding the remaining Tully forces (who were not present at the massacre of their Northern allies) pulled back to Riverrun castle - where they have been hopelessly besieged by House Frey's army ever since. The garrison is under the command of Robb Stark's great-uncle Brynden "The Blackfish" Tully, and is the last bastion of Robb's short-lived independent kingdom that remains unconquered. Riverrun's garrison may be surrounded and alone, fighting for a dead king, but their defenses are formidable, they have enough food supplies to last for years, and their commander is one of the most experienced and skilled generals in Westeros. The Lannisters and their Frey allies cannot let the siege of Riverrun continue to drag on if they are ever to claim real control over central Westeros.</p>
            <p>In Dorne, Ellaria Sand's poisoning of Cersei's daughter, the Princess Myrcella, may now force Doran Martell into the war against the Iron Throne he has been fervently trying to avoid.</p>
            <p>Across the Narrow Sea, in the Free City of Braavos, Arya Stark killed Meryn Trant without the Faceless Men's permission — but without the proper training, the use of one of their masks has poisoned her and rendered her blind. Her training continues, as now the blind little girl must learn to rely on her other senses to survive.</p>
            <p>In Slaver's Bay, Daenerys Targaryen's attempt to liberate Meereen has resulted in massive bloodshed, with the former slave masters conspiring to retake the city. In a large scale ambush on the opening day of the games in Daznak's Pit however, Daenerys climbed onto Drogon's back to try to escape the danger — but she could not make him return to the city. Instead, the young dragon flew north to the southern border of the Dothraki Sea, the lands of his birth, where the stranded Daenerys has been surrounded by a hostile Dothraki khalasar numbering in the thousands. Jorah Mormont and Daario Naharis have set out to search for her. Meanwhile, back in the city Daenerys's advisors Tyrion Lannister, Missandei, and Grey Worm are joined by Varys in attempting to hold together rule over the city wracked by the ongoing insurgency until Daenerys returns — if she returns at all.</p>
            <p>At the Wall, Lord Commander Jon Snow attempted to prepare for the coming of the White Walkers by letting as many wildlings through to the south as he could — but tens of thousands more were killed and resurrected as undead wights at Hardhome. The leading Night's Watch officers, increasingly upset at Jon's proposed alliance with the wildlings, have staged a mutiny "for the Watch" and stabbed Jon multiple times until he fell.</p>
            <p>Just before the mutiny against Jon Snow, he sent away Samwell Tarly to go to the Citadel in Oldtown in order to train to be a new maester to replace Maester Aemon after his passing. Samwell takes Gilly and her young son with him, rather than leave them in the path of the White Walkers. Oldtown, Westeros's second largest city, is located in the southwest of the Reach, not far away from Sam's former home, the House Tarly castle-seat at Horn Hill. Samwell and Gilly, however, face a long and difficult sea voyage before they get to the Citadel.</p>
            <p>Distracted by the political intrigues in King's Landing, the exhausted lords of Westeros must now brace for the rise of the kraken — the ironborn led by House Greyjoy. Early in the War of the Five Kings, Balon Greyjoy declared the Iron Islands' independence and raided the North while the Stark's army was fighting in the south. Having remained relatively uninvolved ever since, the ironborn's massive fleet remains at full strength, a fact lost on the major powers of the mainland, who have been nearly exhausted fighting each other.</p>
            <p>All of this changes with the sudden return of Balon's exiled younger brother Euron Greyjoy — cunning, ruthless, manipulative, and more than a little insane, he strikes fear even into the other ironborn. He pushes for the ironborn to launch massive new offensives against the other kingdoms, not simply to raid, but to hold and conquer territory, as Euron's ultimate ambition is nothing less than to conquer all of the Seven Kingdoms. He is opposed by Balon's daughter Yara Greyjoy, who urges that the Iron Islands must preserve their strength and engage in diplomacy with the mainland if they are to survive.</p>
            <p>And as the winds of winter begin to sweep through the south, far Beyond the Wall the young Bran Stark has been staying with the last of the Children of the Forest and his new mentor, the Three-eyed raven, in order to hone his abilities. Bran will not walk again, but he has learned to fly.</p>
        </div>

        <div className="story_season"></div>
        <h2>Season 7</h2>
            <p>After a summer lasting almost ten years, the words of House Stark have finally become reality once again: winter is here.</p>
            <p>In King's Landing, Cersei Lannister has finally seized the power that she has craved for many years. In one swift move, she has eliminated nearly all of her enemies, rivals, and obstructions; Queen Margaery Tyrell, Lord Mace Tyrell, Ser Loras Tyrell, Cersei's uncle Ser Kevan Lannister, Grand Maester Pycelle, the High Sparrow, and most of - if not all - members of the Faith Militant were killed when the Great Sept of Baelor was destroyed using large amounts of wildfire, an event orchestrated by Cersei. She has crowned herself the undisputed Queen of the Seven Kingdoms, with Qyburn as her Hand and the undead knight Ser Gregor Clegane at her side. After nearly four decades of serving as the power behind the throne, House Lannister has finally become the new royal house. However, Cersei is still haunted by the prophecy she was told during her childhood, which claimed that the deaths of her three (future) children would predate her own; Joffrey, Myrcella, and Tommen are all dead, Tommen having taken his own life shortly after the Sept's destruction. This has made Cersei all the more determined to crush her enemies once and for all, but the number of her enemies has just increased exponentially. Though she now sits on the Iron Throne, she has effectively undone all of Tywin Lannister's efforts to ensure that his family stay in power as her actions have undoubtedly earned her the hatred of all of Westeros. Most of the realm is either in open rebellion against the Iron Throne or has fallen out of her allies' control, leaving Cersei effectively as the Queen of King's Landing and the lands owned by the Lannisters. It is the beginning of the end.</p>
            <p>In the Riverlands, the last bastion of Robb Stark's independent Northern-Riverland kingdom, Riverrun, has fallen to House Lannister and House Frey in a siege led by Ser Jaime Lannister. Lord Edmure Tully, who had been held hostage by the Freys ever since the Red Wedding, ordered the Tully garrison to stand down for the sake of his wife and child, whom Jaime had violently threatened if Edmure refused to cooperate. Edmure's uncle, Brynden "The Blackfish" Tully, is dead, having chosen to fight to the death rather than surrender. Brienne of Tarth and her squire, Podrick Payne, had traveled to Riverrun in an attempt to recruit the Blackfish to assist Sansa Stark in reclaiming Winterfell from House Bolton. The attempt failed, and they were only barely able to escape when the castle fell.</p>
            <p>Although House Frey has reclaimed Riverrun, Lord Walder Frey is also dead. Arya Stark, despite nearly being killed by the Waif and ultimately overcoming the assassin in single combat, has completed her training as a Faceless Man in the Free City of Braavos. With her original mission clearly back in focus, she has abandoned the Order and returned to Westeros to cross more names off of her list of vengeance, starting with Walder Frey, the last surviving orchestrator of the Red Wedding that claimed the lives of her mother, brother, and pregnant sister-in-law, at the same time butchering Walder's two most prominent sons, Lothar Frey and Walder Rivers who also helped carry out the massacre, and leaving the rule of the Riverlands in unknown hands. Also, Sandor "The Hound" Clegane has survived his brutal fight with Brienne of Tarth and attempted to build a new, humble life, but has been dragged back into conflict by the Brotherhood Without Banners, who intend to head north to fight in the war that is coming.</p>
            <p>On the Iron Islands, King Balon Greyjoy is dead, having been murdered by his psychopathic younger brother, Euron Greyjoy. Balon's son, Theon, returned to the Iron Islands after helping Sansa Stark escape from Ramsay Bolton and endorsed his elder sister, Yara, as their father's successor at the subsequent Kingsmoot. However, Euron has claimed and won the Salt Throne by promising an alliance with Daenerys Targaryen, which he will use to conquer the Seven Kingdoms. In desperation, and in fear for their lives, Theon and Yara have stolen a hundred ships from the Iron Fleet. With sailors and soldiers loyal to them, they have traveled to Meereen and sought out Daenerys's help first. They have managed to secure an alliance between House Targaryen and House Greyjoy to help Daenerys retake the Iron Throne and overthrow Euron in return for the Iron Islands' independence. Euron, however, has ordered the construction of an even bigger fleet to begin his own invasions, seek out new alliances and destroy all who may stand in his way of taking the Seven Kingdoms for himself.</p>
            <p>Also aiding Daenerys are the Dornish and the Tyrells, the rulers of the Reach. In Dorne, Ellaria Sand and the Sand Snakes have staged a coup; they have murdered Prince Doran Martell and his heir, Trystane, and taken control of Dorne in retaliation for Doran's refusal to wage war against House Lannister after the brutal death of his younger brother Prince Oberyn at the hands of Ser Gregor, who also murdered their sister Princess Elia and her two young children, Princess Rhaenys and Prince Aegon. With Cersei declaring war against the Sands for their murder of her daughter Myrcella, Ellaria has turned to Daenerys and her loyalists to help bring down the Lannisters. Unknown to Ellaria, however, is that Tyrion Lannister, Myrcella's uncle, is now serving as Daenerys's Hand of the Queen, and will likely demand justice against the Sands for murdering his beloved niece in cold blood. Lady Olenna Tyrell, herself now a target of Cersei as she is now the only surviving Tyrell, has met with Ellaria and the Sand Snakes, a meeting facilitated by Varys. Although skeptical of their motives (and wary that they essentially murdered their own family to seize power), grief-stricken and incensed by the deaths of her son, grandson, and granddaughter, Olenna pledges House Tyrell's forces to Daenerys in the hope of revenge for her slain family, no longer caring about her own survival.</p>
            <p>In the North, Jon Snow and Sansa Stark, aided by Ser Davos Seaworth, Tormund Giantsbane, and Lady Lyanna Mormont, have finally defeated Ramsay Bolton and reclaimed Winterfell following a spectacular battle. Their victory was also due in large part to the support from the knights of the Vale, the elite soldiers of House Arryn, the lords of the Vale, courtesy of Lord Petyr "Littlefinger" Baelish. Even though House Bolton is now extinct following Ramsay's brutal execution, the future of House Stark is left in question: with Robb and Rickon dead, and Bran believed dead as well, the Northern and Vale lords have turned to Jon and named him the new King in the North, while Sansa has rejected Littlefinger's proposal to help him take the Iron Throne and become his queen. Given that Littlefinger was instrumental in the outbreak of the War of the Five Kings (by conspiring with Lysa Arryn to murder Jon Arryn, pit the Starks and Lannisters against each other, and throw Westeros into complete chaos), and that one of his initial goals was to become the new Warden of the North, Jon's ascension to King in the North is now a major obstacle in his master plan, setting the stage for a looming conflict between Jon and Littlefinger, the latter already having sewn seeds of distrust in Sansa towards Jon. The Red Priestess Melisandre, meanwhile, has been dismissed from Jon's service following the discovery of her role in Shireen Baratheon's death, as well as for the burning of countless innocent people as sacrifices to the Lord of Light during her service to Stannis Baratheon, stripping Jon of easily one of his most valuable advisers, and is now heading south to locations unknown.</p>
            <p>In the Reach, after navigating various obstacles, Samwell Tarly, Gilly, and her son have finally reached the Citadel in Oldtown, where Sam intends to train as a maester to replace the deceased Maester Aemon of the Night's Watch, hoping to gain some insight into the White Walkers and how to defeat them. However, with Sam's theft of his family's ancestral Valyrian steel sword, Heartsbane, he has undoubtedly incurred the immense wrath of his father, Randyll Tarly, who will now likely seek retribution, while the absence House Tyrell's armies will have also left the Reach open to coming outside attacks, so Samwell must use the sword in his studies and uncover the secrets behind Valyrian steel for the coming battle against the dead, before all is lost.</p>
            <p>Across the Narrow Sea, having at last defeated the slave masters and the Sons of the Harpy, Queen Daenerys Targaryen has finally set sail for Westeros. She has acquired an army consisting of the Unsullied, the Dothraki, and troops from House Greyjoy, House Tyrell, Dorne, and her three full-grown dragons. Tyrion Lannister serves at her side as Hand of the Queen, though at the cost of two of her advisors: Ser Jorah Mormont, whom Daenerys has sent to find a cure for his spreading greyscale infection, and Daario Naharis, her lover whom Daenerys has ordered to stay behind with the Second Sons (on Tyrion's advice) so that she may pursue a potential marriage alliance to aid her in her campaign. Unknown to Daenerys, however, there is already somebody across the Narrow Sea who may very well have a stronger claim to the Targaryen monarchy than she does, and who may prove to become her most valuable ally or her greatest enemy yet.</p>
            <p>Beyond the Wall, Bran Stark has been training in his power of greensight under the tutelage of the Three-Eyed Raven and has learned some devastating secrets, specifically the origin of the White Walkers and the true parentage of his believed half-brother, Jon Snow: Jon is the son of Lyanna Stark and Prince Rhaegar Targaryen, which would make him the nephew and a rival claimant to Daenerys Targaryen for the Iron Throne. Following an attack which claims the lives of the Three-Eyed Raven, Hodor, and seemingly the last of the Children of the Forest, Bran and Meera Reed have been rescued by Bran's undead uncle, Benjen Stark, and taken back to the Wall. There, Bran must prepare for the arrival of the Night King, who at all costs must be defeated before Westeros can dream of another spring.</p>
      </div>
    )
  }
}

export default Story
